version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: kd-gen
    main: ./main.go
    binary: kd-gen
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

brews:
  - name: kd-gen
    repository:
      owner: khuong02   # your GitHub username
      name: homebrew-tap
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    homepage: "https://github.com/khuong02/kd-gen"
    description: "A Go code generator for enums."
    license: "MIT"
    install: |
      bin.install "kd-gen"

archives:
  - format: tar.gz
    builds: [ kd-gen ]
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  replace_existing_draft: true
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
