version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: kd-gen
    main: ./main.go
    binary: kd-gen
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

brews:
  - name: kd-gen
    repository:
      owner: khuong02   # your GitHub username
      name: homebrew-tap
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    homepage: "https://github.com/khuong02/kd-gen"
    description: "A Go code generator for enums."
    license: "MIT"


archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
