name: PR Checks

on:
  pull_request:
    branches:
    - main
    - release/**
    - fix/**
    - hotfix/**
    - infra/**

jobs:

  # ---- Lint ----
  lint:
    runs-on: ubuntu-latest
    environment: KD-GEN
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.25

      - name: Install golangci-lint v2
        run: |
          go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.1.0
          golangci-lint --version

      - name: Run golangci-lint
        run: |
          if golangci-lint run ./...; then
            echo "result=success" >> $GITHUB_OUTPUT
          else
            echo "result=failure" >> $GITHUB_OUTPUT
            exit 1
          fi

  # ---- Security ----
  sec:
    runs-on: ubuntu-latest
    environment: KD-GEN
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.25

      - name: Install gosec
        run: |
          go install github.com/securego/gosec/v2/cmd/gosec@latest
          gosec --version

      - name: Run gosec
        run: |
          if gosec ./...; then
            echo "result=success" >> $GITHUB_OUTPUT
          else
            echo "result=failure" >> $GITHUB_OUTPUT
            exit 1
          fi

  summary:
    runs-on: ubuntu-latest
    needs: [ lint, sec ]
    if: always() # ensure it runs even if lint/sec fail
    steps:
      - name: Create summary
        run: |
          echo "## ✅ PR Checks Summary" >> $GITHUB_STEP_SUMMARY

          if [[ "${{ needs.lint.result }}" == "success" ]]; then
            echo "- **Lint**: ✅ Passed" >> $GITHUB_STEP_SUMMARY
          else
            echo "- **Lint**: ❌ Failed" >> $GITHUB_STEP_SUMMARY
          fi

          if [[ "${{ needs.sec.result }}" == "success" ]]; then
            echo "- **Security**: ✅ Passed" >> $GITHUB_STEP_SUMMARY
          else
            echo "- **Security**: ❌ Failed" >> $GITHUB_STEP_SUMMARY
          fi
