name: PR Checks

on:
  pull_request:
    branches:
    - main
    - release/**
    - fix/**
    - hotfix/**
    - infra/**

jobs:

  # ---- Lint ----
  lint:
    runs-on: ubuntu-latest
    environment: KD-GEN
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.25

      - name: Install golangci-lint v2
        run: |
          go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.1.0
          golangci-lint --version

      - name: Run golangci-lint
        run: golangci-lint run ./...

  # ---- Security ----
  sec:
    runs-on: ubuntu-latest
    environment: KD-GEN
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.25

      - name: Install gosec
        run: |
          go install github.com/securego/gosec/v2/cmd/gosec@latest
          gosec --version

      - name: Run gosec
        run: gosec ./...
