name: PR Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  # ---- Check PR Title ----
  title-check:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_TOKEN }}
        with:
          types: |
            feat
            fix
            hotfix
            infra

  # ---- Lint ----
  lint:
    runs-on: ubuntu-latest
    needs: title-check   # ✅ chỉ chạy khi title-check pass
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.25

      - name: Install golangci-lint v2
        run: |
          go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@latest
          golangci-lint --version

      - name: Run golangci-lint
        run: golangci-lint run ./...

  # ---- Security ----
  sec:
    runs-on: ubuntu-latest
    needs: title-check   # ✅ chỉ chạy khi title-check pass
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.25

      - name: Install gosec
        run: |
          go install github.com/securego/gosec/v2/cmd/gosec@latest
          gosec --version

      - name: Run gosec
        run: gosec ./...
